### ISSUE TITLE
Possibly reentrancy attack

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#1]
# StandardToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/StandardToken.sol#L47
```
balances[_to] = safeAdd(balances[_to],_value);
balances[_from] = safeSub(balances[_from],_value);
```

These two lines should be swapped to prevent code re-entrancy attacks

**Comment by rstormsf** [comment]
still not fixed in https://github.com/chronologic/chronologic/blob/dev/contracts/StandardToken.sol#L47

**Comment by matt-lough** [comment]
Still not fixed https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L444-L445
