### ISSUE TITLE
DRY mintingPowerByAddress

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#10]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L217
`function getMintingPowerByAddress` is repeating code from `function getMintingPowerById`

Change the contents of the `getMintingPowerByAddress` function to:

`return getMintingPowerById(idOf[_adr]);`

**Comment by matt-lough** [comment]
The `balanceOf` and `balanceById` functions have a similar problem

**Comment by rstormsf** [comment]
Not fixed

**Comment by matt-lough** [comment]
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L343

https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L401

Both fixed.
