### ISSUE TITLE
Expected total coins minted to be a uint, an int is returned

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#11]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L234
`function getTotalMinted(address _adr) public constant returns (int256) {`

This function returns the number of DAY tokens minted, using the type `int` which means that it expects there could be a negative amount. Is this correct?

**Comment by rstormsf** [comment]
Fixed:
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L345
