### ISSUE TITLE
updateBalanceOf should return a bool

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#12]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L259
`function updateBalanceOf(uint256 _id) internal returns (bool success) {`

This function should always return a bool, it only returns true, and never false.

**Comment by rstormsf** [comment]
Fixed https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L382
