### ISSUE TITLE
DRY isContributor

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#13]
# DayToken.sol

There is a pattern used throughout this file for identifying if an ID is a contributor. The modifier `onlyContributor` uses it, and several other functions use it too. In the interest of not repeating yourself, a function should be created like

```
function isContributor(uint id) returns (bool isContributor) {
    return (id <= latestContributerId && id != 0);
}
```

**Comment by rstormsf** [comment]
Not implemented. the issue still exists

**Comment by rohendra** [comment]
@rstormsf It is fixed. Function name is changed to isValidContributorId.

**Comment by matt-lough** [comment]
Fixed https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L224
