### ISSUE TITLE
Transfer is not behaving correctly

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#14]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L380
`balances[_to] = safeAdd(balances[msg.sender], _value);`

When you make a transfer, the receivers balance will be equal to the senders balance plus the value sent, instead of the receivers balance plus the value sent.

The correct code would be:

`balances[_to] = safeAdd(balances[_to], _value);`

This error could inadvertently burn or clone all tokens in existence. If you make a transfer to the owner/team multisig address from an address with a small number of tokens, the entire supply other than the small number of tokens will be lost completely.

You could also clone tokens by transferring from a high balance address, to a low balance address.

**Comment by rstormsf** [comment]
Fixed.
https://github.com/chronologic/chronologic/blob/007cdecfc51495689e591d821c07cbef80a4e284/contracts/DayToken.sol#L493
