### ISSUE TITLE
Potential re-entrancy attack

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#16]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L414
```
balances[_to] = safeAdd(balances[_to], _value);
balances[_from] = safeSub(balances[_from], _value);
allowed[_from][msg.sender] = safeSub(_allowance, _value);
```

Subtractions should be made before addition to prevent a re-entrancy attack. We recommend re-ordering these lines.

**Comment by rstormsf** [comment]
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L528 fixed
