### ISSUE TITLE
Another re-entrancy attack

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#18]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L515

```
balances[this] = safeAdd(balances[this], minBalanceToSell);
balances[msg.sender] = safeSub(balances[msg.sender], minBalanceToSell);
```

**Comment by rstormsf** [comment]
fixed.
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L612
