### ISSUE TITLE
Issue with sellMintingAddress

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#19]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L501

`sellMintingAddress` isn't transferring the actual amount specified by the user, instead it's transferring `minBalanceToSell`

**Comment by rstormsf** [comment]
@matt-lough Could you please clarify what you mean

**Comment by IsaacPayne** [comment]
Updated link as it was point to the wrong function

**Comment by rstormsf** [comment]
I can verify that the issue is still not fixed:
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L612

**Comment by rohendra** [comment]
@rstormsf 
The seller of MintingAddress puts their address on Sale by calling **sellMintingAddress** function specifying minimum price **_minPriceInDay** they will sell it for. Their is a requirement that seller has to transfer **minBalanceToSell** day tokens to the contract and it will be locked till someone buys that address or sale period expires. If some one buys then seller gets priceOffered by buyer + **minBalanceToSell** in his account, else he only gets **minBalanceToSell** back in his account.

**Comment by matt-lough** [comment]
@rohendra The logic sounds okay to me, closing this issue.
