### ISSUE TITLE
Re-entracy issue

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#20]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L549-L550

**Comment by rstormsf** [comment]
Fixed:
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L648-L649
