### ISSUE TITLE
Value mismatch when purchasing minting address

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#21]
https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L547-L550

The logic in the comment above does not match with the code, the `minBalanceToSend` is not added to `_offerInDay`

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L566-L567

This line of code does match the comment from above, which means one of these is wrong. 

In this current state you be able to withdraw more than you sold for.

**Comment by rohendra** [comment]
rejected:  minBalanceToSell is subtracted from seller in sellMintingAddress() method and deposited with contract

**Comment by rstormsf** [comment]
I agree with @matt-lough You will be able to withdraw more than you sold. 
@rohendra Please write a Unit test for it to prove otherwise.

**Comment by IsaacPayne** [comment]
This still seems to be an issue:

From `buyMintingAddress`
```
        balances[msg.sender] = safeSub(balances[msg.sender], _offerInDay);
        balances[this] = safeAdd(balances[this], _offerInDay);
```

From `fetchSuccessfulSaleProceed`
```
        uint saleProceed = safeAdd(minBalanceToSell, sellingPriceInDayOf[msg.sender]);
        balances[this] = safeSub(balances[this], saleProceed);
        balances[msg.sender] = safeAdd(balances[msg.sender], saleProceed);
```

Why are we adding `minBalanceToSell` when fetching?

**Comment by rohendra** [comment]
To put Minting address on sale, seller has to initially deposit **minBalanceToSell** tokens with contract which he gets backs along with the **_offerInDay** tokens which is paid by buyer.

see **sellMintingAddress**
        balances[msg.sender] = safeSub(balances[msg.sender], minBalanceToSell);
        balances[this] = safeAdd(balances[this], minBalanceToSell);

**Comment by matt-lough** [comment]
If @rohendra is happy with this behaviour then I'm happy to close this issue.
