### ISSUE TITLE
A minting address is never set to status SOLD

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#22]
https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L23

The `SOLD` status is never used, this should be removed, or used.

**Comment by rstormsf** [comment]
The issue still exists

**Comment by rohendra** [comment]
I have removed SOLD from enum because it is not needed
as soon as an address is sold, it is eligible to be sold again, hence status changes to ONSALE or NOTONSALE

**Comment by matt-lough** [comment]
Fixed in [commit 007cdec](https://github.com/chronologic/chronologic/commit/007cdecfc51495689e591d821c07cbef80a4e284)
