### ISSUE TITLE
Recommend using the shortcut variable that was created

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#23]
https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L588-L590

This variable was created a few lines above, use this instead of repeating yourself.

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L578

**Comment by rstormsf** [comment]
Fixed:
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L688-L690
