### ISSUE TITLE
Magic numbers used in several functions

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#24]
Examples:

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L598

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L617-L619

https://github.com/BlockchainLabsNZ/chronologic/blob/3ba1fe830881ca9e85f2c2db3e77b3b333bc4dd1/contracts/DayToken.sol#L457-L466

We would recommend using a static variable for these numbers so you can tell what they are meant to be, and change them easily if needed.

**Comment by matt-lough** [comment]
https://github.com/chronologic/chronologic/blob/dev/contracts/Crowdsale.sol#L182-L188

**Comment by rstormsf** [comment]
Fixed and verified
