### ISSUE TITLE
Simplify Conditional logic

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#3]
# StandardToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/StandardToken.sol#L68
`require(!((_value != 0) && (allowed[msg.sender][_spender] != 0)));`

The above line could be simplified to 

`require((_value == 0) || (allowed[msg.sender][_spender] == 0));`

Which is much easier to read.

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L50

**Comment by rstormsf** [comment]
Fixed and verified:
https://github.com/chronologic/chronologic/blob/dev/contracts/StandardToken.sol#L68
