### ISSUE TITLE
ERC20 Token Standard Consistency

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#4]
# ERC20.sol and ERC20Basic.sol

The names of the parameters deviate from the standard naming conventions in ERC20 Token Standard. We would recommend following them exactly.

[ERC20 Token Standard](https://theethereum.wiki/w/index.php/ERC20_Token_Standard)

Example: 

_ERC20Basic.sol_
`function balanceOf(address who) constant returns (uint);`

_ERC20 Token Standard_
`function balanceOf(address _owner) constant returns (uint balance);`

**Comment by rstormsf** [comment]
https://github.com/chronologic/chronologic/blob/007cdecfc51495689e591d821c07cbef80a4e284/contracts/ERC20Basic.sol#L9 fixed
https://github.com/chronologic/chronologic/blob/007cdecfc51495689e591d821c07cbef80a4e284/contracts/ERC20.sol#L8 fixed
