### ISSUE TITLE
Gender neutral language is recommended

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#5]
# UpgradeableToken.sol

`* Somebody has upgraded some of his tokens.`

Should probably say

`* Somebody has upgraded some of their tokens.`

# DayToken.sol

`/** Funtion to allow seller to get back his deposited amount of day tokens...`

to

`/** Function to allow seller to get back their deposited amount of day tokens...`

etc

**Comment by rstormsf** [comment]
https://github.com/chronologic/chronologic/blob/dev/contracts/DayToken.sol#L658 fixed
https://github.com/chronologic/chronologic/blob/dev/contracts/UpgradeableToken.sol#L37 fixed
