### ISSUE TITLE
Safe math functions should be constant

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#6]
Add Constant modifier to SafeMath functions as they don't modify storage

**Comment by rstormsf** [comment]
Fixed and verified in:
https://github.com/chronologic/chronologic/commit/007cdecfc51495689e591d821c07cbef80a4e284#diff-f24e42beaec6bfea5b198faed59e4d33R4 
I'd also add `internal` modifier
