### ISSUE TITLE
FlatPricing strategy can be initialized in an invalid state

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#7]
# FlatPricing.sol

We would recommend adding `require(_oneTokenInWei > 0)` in the constructor, you should not be able to declare this variable to 0 because it will break the calculatePrice function.

**Comment by rstormsf** [comment]
https://github.com/chronologic/chronologic/blob/007cdecfc51495689e591d821c07cbef80a4e284/contracts/FlatPricing.sol#L15 fixed
